#!/usr/bin/env python3
"""Turns the kernel's VGA 8x16 console font into src/font8x16.h.

The font is lib/fonts/font_8x16.c from Linux: the classic VGA text-mode
font in CP437 order, which is where the box-drawing glyphs come from.
"""
import re, sys, pathlib

src = pathlib.Path(sys.argv[1]).read_text()
body = src[src.index("FONTDATAMAX"):]
data = [int(m, 16) for m in re.findall(r"0x([0-9a-fA-F]{2}),", body)]
if len(data) < 4096:
    raise SystemExit(f"expected 4096 bytes, parsed {len(data)}")
data = data[:4096]

out = ["/* Generated by tools/mkfont.py - do not edit.",
       " *",
       " * The VGA 8x16 text-mode font, taken from lib/fonts/font_8x16.c in",
       " * Linux (SPDX: GPL-2.0). CP437 order, so 0xB3..0xDA are the",
       " * box-drawing glyphs the UI is built from.",
       " */",
       "#ifndef PL_FONT8X16_H",
       "#define PL_FONT8X16_H",
       "",
       "#define FONT_W 8",
       "#define FONT_H 16",
       "",
       "static const unsigned char font8x16[4096] = {"]
for i in range(0, 4096, 16):
    glyph = ", ".join(f"0x{b:02x}" for b in data[i:i+16])
    out.append(f"\t{glyph},  /* {i//16:3d} 0x{i//16:02X} */")
out += ["};", "", "#endif"]
pathlib.Path("src/font8x16.h").write_text("\n".join(out) + "\n")
print(f"src/font8x16.h: {len(data)} bytes, {len(data)//16} glyphs")
