#!/usr/bin/env python3
"""Generates src/unifont.c and src/unifont.h: the glyphs and the tables
the launcher draws text beyond ASCII with (docs/japanese.md).

    python3 tools/mkunifont.py unifont_jp-18.0.01.hex izmg16-plane00.hex

unifont_jp-18.0.01.hex is the Japanese build of GNU Unifont, from
https://unifoundry.com/pub/unifont/unifont-18.0.01/font-builds/, and
izmg16-plane00.hex is font/plane00/ in unifont-18.0.01.tar.gz from the
directory above it: the public domain Izumi16 glyphs unifont_jp is built
with. FONTS.md has the notice.

What is generated:
  - the Unifont set: every character of JIS X 0213 the VGA font does not
    have, with its unifont_jp glyph, 8 or 16 pixels wide;
  - the VGA map: Unicode to CP437, for the glyphs font8x16.h already has;
  - compositions: a base and a combining mark to the character they make,
    for every character either font draws;
  - base letters: a character neither font draws, to the drawn character
    its canonical decomposition starts with;
  - the combining marks, as ranges.
The Unicode data is this Python's unicodedata; its version is recorded.
"""
import os, sys, unicodedata

def read_hex(path):
    out = {}
    for line in open(path):
        if ":" in line and not line.startswith("#"):
            cp, bits = line.strip().split(":")
            out[int(cp, 16)] = bits
    return out

def jis_x_0213(cp):
    try:
        return len(chr(cp).encode("euc_jis_2004")) >= 2
    except UnicodeEncodeError:
        return False

unifont, izumi = read_hex(sys.argv[1]), read_hex(sys.argv[2])

# CP437's glyphs above ASCII, by their Unicode. 0x1C-0x1F are the shape
# marks (term.h) and are never reached from text.
LOW = "☺☻♥♦♣♠•◘○◙♂♀♪♫☼►◄↕‼¶§▬↨↑↓→←"
assert len(LOW) == 0x1B
vga = {ord(c): i + 1 for i, c in enumerate(LOW)}
vga[0x2302] = 0x7F
for b in range(0x80, 0x100):
    vga[ord(bytes([b]).decode("cp437"))] = b

uni = {}
for cp, bits in unifont.items():
    if cp < 0x80 or cp in vga or (0xD800 <= cp < 0xE000):
        continue
    if unicodedata.combining(chr(cp)):    # composed or dropped, never drawn
        continue
    if len(bits) in (32, 64) and jis_x_0213(cp):
        uni[cp] = bits

drawable = set(range(0x20, 0x7F)) | set(vga) | set(uni)

comp = []
for cp in sorted(drawable):
    d = unicodedata.decomposition(chr(cp))
    if not d or d.startswith("<"):
        continue
    parts = [int(x, 16) for x in d.split()]
    if len(parts) == 2 and unicodedata.combining(chr(parts[1])):
        comp.append((parts[0], parts[1], cp))
comp.sort()

base = []
for cp in range(0x80, 0x30000):
    if cp in drawable or 0xD800 <= cp < 0xE000:
        continue
    x = cp
    for _ in range(6):
        d = unicodedata.decomposition(chr(x))
        if not d or d.startswith("<"):
            break
        x = int(d.split()[0], 16)
        if x in drawable:
            base.append((cp, x))
            break

ranges, start = [], None
for cp in range(0, 0x30000):
    on = not (0xD800 <= cp < 0xE000) and unicodedata.combining(chr(cp)) != 0
    if on and start is None:
        start = cp
    if not on and start is not None:
        ranges.append((start, cp - 1))
        start = None

own = [cp for cp in sorted(uni) if izumi.get(cp) != uni[cp]]
def spans(cps):
    out, s, p = [], None, None
    for c in cps:
        if s is None:
            s = p = c
        elif c == p + 1:
            p = c
        else:
            out.append((s, p)); s = p = c
    if s is not None:
        out.append((s, p))
    return " ".join(f"U+{a:04X}" if a == b else f"U+{a:04X}-{b:04X}" for a, b in out)

src = os.path.join(os.path.dirname(__file__), "..", "src")
keys = sorted(uni)
with open(os.path.join(src, "unifont.h"), "w") as h:
    h.write(f"""/* Generated by tools/mkunifont.py - do not edit. The data is in
 * unifont.c; glyph.h is what the rest of the program uses. */
#ifndef PL_UNIFONT_H
#define PL_UNIFONT_H

#include <stdint.h>

#define UNI_N   {len(keys)}
#define VGA_N   {len(vga)}
#define COMP_N  {len(comp)}
#define BASE_N  {len(base)}
#define COMB_N  {len(ranges)}
#define UNI_WIDE 0x80000000u   /* in uni_key: the glyph is 16 pixels wide */

extern const uint32_t uni_key[UNI_N];          /* code point | UNI_WIDE, sorted */
extern const unsigned char uni_bits[UNI_N][32]; /* 16 rows; 8 wide uses 16 bytes */
extern const uint16_t vga_map[VGA_N][2];       /* Unicode, CP437 code; sorted  */
extern const uint32_t comp_map[COMP_N][3];     /* base, mark, composed; sorted */
extern const uint32_t base_map[BASE_N][2];     /* character, its base; sorted  */
extern const uint32_t comb_ranges[COMB_N][2];  /* combining marks, first, last */

#endif
""")
with open(os.path.join(src, "unifont.c"), "w") as f:
    f.write(f"""/* Generated by tools/mkunifont.py - do not edit.
 *
 * Glyphs from GNU Unifont 18.0.01, the Japanese build unifont_jp:
 * Copyright (C) 1998-2026 Roman Czyborra, Paul Hardy, Qianqian Fang,
 * Andrew Miller, Johnnie Weaver, David Corbett, Aella Chiana Moskopp,
 * Rebecca Bettencourt, Minseo Lee, Ho-Seok Ee, et al.
 *
 * {len(keys) - len(own)} of the {len(keys)} glyphs are the public domain Izumi16 font's. The
 * other {len(own)} are Unifont's own, used here under the GPL 2.0 or later
 * with the GNU font embedding exception; FONTS.md has the notice. They are:
 *
 * """)
    line = ""
    for word in spans(own).split():
        if len(line) + len(word) + 1 > 72:
            f.write(line + "\n * ")
            line = ""
        line += ("" if not line else " ") + word
    f.write(line + f"""
 *
 * Unicode data: Python unicodedata {unicodedata.unidata_version}.
 */
#include "unifont.h"

const uint32_t uni_key[UNI_N] = {{
""")
    for i in range(0, len(keys), 6):
        f.write("\t" + ", ".join(
            f"0x{cp | (0x80000000 if len(uni[cp]) == 64 else 0):08x}" for cp in keys[i:i + 6]) + ",\n")
    f.write("};\n\nconst unsigned char uni_bits[UNI_N][32] = {\n")
    for cp in keys:
        bits = uni[cp].ljust(64, "0")
        f.write("\t{" + ",".join(f"0x{bits[i:i + 2]}" for i in range(0, 64, 2)) +
                f"}},  /* U+{cp:04X} */\n")
    f.write("};\n\nconst uint16_t vga_map[VGA_N][2] = {\n")
    for u, c in sorted(vga.items()):
        f.write(f"\t{{ 0x{u:04x}, 0x{c:02x} }},\n")
    f.write("};\n\nconst uint32_t comp_map[COMP_N][3] = {\n")
    for b, m, c in comp:
        f.write(f"\t{{ 0x{b:04x}, 0x{m:04x}, 0x{c:04x} }},\n")
    f.write("};\n\nconst uint32_t base_map[BASE_N][2] = {\n")
    for c, b in base:
        f.write(f"\t{{ 0x{c:04x}, 0x{b:04x} }},\n")
    f.write("};\n\nconst uint32_t comb_ranges[COMB_N][2] = {\n")
    for a, b in ranges:
        f.write(f"\t{{ 0x{a:04x}, 0x{b:04x} }},\n")
    f.write("};\n")
print(f"wrote src/unifont.c: {len(keys)} glyphs ({len(own)} Unifont's own), "
      f"{len(vga)} VGA, {len(comp)} compositions, {len(base)} base letters, "
      f"{len(ranges)} combining ranges; Unicode {unicodedata.unidata_version}")
