/* What there is to play.
 *
 * Read from the files EmulationStation already uses, because they are
 * generated by the build and are the definition of what this device can run:
 *
 *   /usr/config/emulationstation/es_systems.cfg  systems, paths, extensions,
 *                                                and the default emulator
 *   /storage/.config/system/configs/system.cfg   per-system overrides, the
 *                                                same keys setsettings.sh reads
 *
 * es_systems.cfg is generated, so a tag scanner is enough and a real XML
 * parser is not. That is a trade rather than a free lunch, and the one place
 * it shows is entity escapes, which are decoded explicitly.
 */
#ifndef PL_CATALOG_H
#define PL_CATALOG_H

struct game {
	char name[192];   /* shown in the list, extension stripped */
	char path[512];
};

struct psystem {
	char name[32];      /* "psx"                            */
	char fullname[72];  /* "Sony PlayStation"               */
	char path[256];     /* /storage/roms/psx                */
	char exts[256];     /* ".cue .chd .pbp"                 */
	char launcher[256]; /* the binary out of <command>      */
	char core[64];
	char emulator[64];
	struct game *games;
	int ngames;
};

struct catalog {
	struct psystem *sys;
	int n;
};

/* Systems with no games are dropped, so the list only shows what can be
 * played. */
int  catalog_load(struct catalog *c, const char *es_systems, const char *settings);
void catalog_free(struct catalog *c);

#endif
