/* Generated by tools/mkunifont.py - do not edit. The data is in
 * unifont.c; glyph.h is what the rest of the program uses. */
#ifndef PL_UNIFONT_H
#define PL_UNIFONT_H

#include <stdint.h>

#define UNI_N   14300
#define VGA_N   156
#define COMP_N  275
#define BASE_N  1255
#define COMB_N  196
#define UNI_WIDE 0x80000000u   /* in uni_key: the glyph is 16 pixels wide */

extern const uint32_t uni_key[UNI_N];          /* code point | UNI_WIDE, sorted */
extern const unsigned char uni_bits[UNI_N][32]; /* 16 rows; 8 wide uses 16 bytes */
extern const uint16_t vga_map[VGA_N][2];       /* Unicode, CP437 code; sorted  */
extern const uint32_t comp_map[COMP_N][3];     /* base, mark, composed; sorted */
extern const uint32_t base_map[BASE_N][2];     /* character, its base; sorted  */
extern const uint32_t comb_ranges[COMB_N][2];  /* combining marks, first, last */

#endif
